STEP 8 SET UP EXPRESS ON THIS PAGE AND GET THE ROUTER FUNCTION FROM EXPRESS GOING
const router = require('express').Router();

STEP 9 ASSIGN HOME
router.route('/').get((req, res) => res.render('home'));

STEP 10 EXPORT
module.exports(rog)

STEP 13 SET UP FIRST VIEWS FILES - LAYOUT.EJS & HOME.EJS SO WE CAN TEST THAT EVERYTHING IS WORKING

STEP 14 FILL OUT YOUR LAYOUT.EJS FILE - LINK CSS LINK THE BODY - ALSO PUT IN A HEADER INTO HOME SO THAT LAYOUT HAS SOMETHING TO PUT INSIDE IT
STEP 15 CHECK THAT ITS WORKING BY GOING TO LOCAL HOST 3000
STEP 16 TEST STYLE - MK PUBLIC DIRECTORY - CSS DIRECTORY - STYLE.CSS - put something random in there to make sure it is working
STEP 17 WE NEED DEPENDENCY SO - BOWER INIT - ENTER EVERYTHING
STEP 18 BOWER INSTALL BOOTSTRAP --SAVE // AUTOMATICALLY DOWNLOADS JQUERY BECAUSE BOOTSTRAP NEEDS IT
19 ANOTHER STATICS DIRECTORY ABOVE PUBLIC TO BE BOWER COMPONENTS
20 LINK LAYOUT.EJS TO BOOSTRAP & JQUERY WITHIN BOOTSTRAP COMPONENTS
21 MAKE PARTIAL FOR OUR HEADER MENU INSIDE THE APPLICATION DIRECTORY WITHIN THE VIEWS DIRECTORY (_HEADER.EJS)
22 CONNECT OUR PARTIAL TO OUR LAYOUT.EJS (_HEADER.EJS)
23 DO A FOOTER PARTIAL AND CONNECT THAT AS WELL
24 TEST TO SEE IF IT WORKS - THERE SHOULD BE NO ERRORS SO ITS TIME TO SET UP OUR REST
25 SET UP BITS OF CSS FOR THE PARTIALS BODY ETC
26 SET UP AN IMAGES FILE IN PUBLIC SO THAT WE CAN ACCESS IT
27 MAKE A RESTFUL RESOURCE - MKDIR MODELS - TOUCH MODELS/MOVIE.JS
28 SET UP THE SCHEMA - REQUIRE MONGOOSE IN MOVIE.JS - movieSchema = NEW MONGOOSE.SCHEMA { TITLE, DESCRIPTION, DIRECTOR }{TIMESTAMPS} - MODULE.EXPORTS = MONGOOSE.MODEL('MOVIE', movieSchema)
29 SET UP A CONTROLLER - MKDIR CONTROLLER - TOUCH CONTRLLER/MOVIES.JS
30 GO INTO CONTROLLER REQUIRE MODELS/MOVIE (OUR MODEL)
31 SET UP FUNCTION WITHIN THE CONTROLLER - MOVIESINDEX(REQ, RES){MOVIE.FIND{}, (ERR, MOVIES) => IF (ERR) RETURN RES.RENDER('MOVIES/INDEX, { MOVIES: {}, ERROR: 'SOMETHING WENT WRONG.' }')}; RETURN RES.RENDER('MOVIES/INDEX', { MOVIES: })
32 MODULE.EXPORTS = { INDEX: MOVIESINDEX}
33 DO THE SAME THING FOR FUNCTION MOVIESNEW - ADD THAT INTO MODULE EXPORTS
34 MKDIR MOVIES IN VIEWS - TOUCH NEW.EJS INTO IT - FILL THAT EJS FILE OUT WITH A FORM AND TEST TO SEE IF IT WORK WITH THE FUNCTION MOVIESNEW  - WE DO NOT HAVE A ROUTE SO IT WONT WORK SO WE NEED TO SET UP A ROUTE FOR NEW.EJS ( IDEALLY YOU SHOULD DO THE ROUTE FIRST THEN THE CONTROLLER THEN THE VIEW )
35 REQUIRE THE CONTROLLER IN THE ROUTES PAGE
36 WE NEED A POST TO ACTUALLY ACTIVE THE NEW.EJS FILE
37 CREATE A POST ROUTE IN THE ROUTER - GO INTO THE CONTROLLER MAKE A NEW FUNCTION FUNCTION MOVIESCREATE - ADD THAT INTO THE MODULE.EXPORTS INDEX
38 SET UP .GET(MOVIES.INDEX)
39 TOUCH VIEWS/MOVIES/INDEX.EJS - ADD CONTENT TO INDEX.EJS - LIST ALL OF THE MOVIES
40





to make another model you need to add another file to the model folder
define a schema 
