# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a0379601d0dc75649df341b4e0a7277f7090c72138d55fbbf371c8c0a691953bed02e71917d9a3e4486e2071b1dabaf8f377e6c9048141c0c912c0d25c2ea8

test:
  secret_key_base: d7ce700b37cc4def2f3da7dac7e88edb014fa415dc6600601fbd5cfec0efd1120fef6088c837ef442543e00aaf9e5f2bc82dd5e0792418ad782dc784dfee3f50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
